### ISSUE TITLE
The job never completes 

### ISSUE THREAD

**Issue by arunsubbu-github** [aws-samples/amazon-textract-code-samples#25]
I ran this code on a sample pdf document but it never completes .   The PDF is valid since it works from the console

When I terminate the job, this is what I get

Started job with id: eb64ef4b16fd56ae8756387b9aff71b1f661a55a6128e5c4de8a2b43c8a2e397
Job status: IN_PROGRESS
^CTraceback (most recent call last):
  File "run.py", line 50, in <module>
    if(isJobComplete(jobId)):
  File "run.py", line 23, in isJobComplete
    time.sleep(5)
KeyboardInterrupt

**Comment by schadem** [comment]
Which code specifically did you run?﻿
